
services:

 

  frontend:
    container_name: frontend
    image: frontend
    build: ./frontend
    ports:
      - "3030:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      # - ./backend/media/images:/usr/share/nginx/html/media/images


